install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\sbt\sbt-launcher-packaging-0.13.13" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://dl.bintray.com/sbt/native-packages/sbt/0.13.13/sbt-0.13.13.zip',
          'C:\sbt-0.13.13.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sbt-0.13.13.zip", "C:\sbt")
      }
  - ps: |
      if (!(Test-Path -Path "C:\Program Files\Java\jdk1.7.0\src.zip")) {
        (new-object System.Net.WebClient).DownloadFile(
          'http://downloads.sourceforge.net/project/jdk7src/jdk7u10/2013-01-04/src-jdk.zip',
          'C:\Program Files\Java\jdk1.7.0\src.zip'
        )
      }
  - cmd: SET JDK_HOME=C:\Program Files\Java\jdk1.7.0
  - cmd: SET JAVA_HOME=C:\Program Files\Java\jdk1.7.0
  - cmd: SET PATH=C:\sbt\sbt-launcher-packaging-0.13.13\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET SBT_HOME=C:\Users\appveyor\.sbt
  - cmd: SET COURSIER_VERBOSITY=-1
  - cmd: SET GC_LOGGING=true
  - cmd: git config core.symlinks true
  - cmd: git reset --hard
build_script:
  - sbt clean compile
test_script:
  - sbt scripted
cache:
  - C:\Program Files\Java\jdk1.7.0\src.zip
  - C:\sbt\sbt-launcher-packaging-0.13.13
  - C:\Users\appveyor\.sbt -> appveyor.yml
  - C:\Users\appveyor\.ivy2 -> appveyor.yml
  - C:\Users\appveyor\.coursier -> appveyor.yml
on_finish:
  - ps: Get-ChildItem -Path .\* -Include *.log,*.hprof -Recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
